# Generated by Django 2.2.5 on 2020-06-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200531_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('email', 'email'), ('kakao', 'kakao'), ('naver', 'naver'), ('facebook', 'facebook')], default='email', max_length=50),
        ),
    ]
