# Generated by Django 2.2.5 on 2020-07-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_login_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adoption_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='foster_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('email', 'email'), ('kakao', 'Kakao'), ('naver', 'Naver'), ('google', 'Google')], default='email', max_length=50),
        ),
    ]
