# Generated by Django 2.2.5 on 2020-05-18 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', '예약 확인 중'), ('confirmed', '예약 확정'), ('canceled', '예약 취소')], max_length=15)),
                ('meeting_time', models.DateTimeField()),
                ('meeting_address', models.CharField(max_length=200)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='docs.Doc')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
