# Generated by Django 2.2.5 on 2020-05-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_auto_20200520_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='reason_adopt',
            field=models.TextField(default='reason why'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='instagram_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
