# Generated by Django 2.2.5 on 2020-05-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vets', '0002_remove_vet_care_taker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vet',
            name='diagnosis',
        ),
        migrations.AddField(
            model_name='vet',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='Diagnosis',
        ),
    ]
