# Generated by Django 2.2.5 on 2020-05-24 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vets', '0003_auto_20200524_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vet',
            old_name='reciept',
            new_name='receipt',
        ),
    ]
