# Generated by Django 2.2.5 on 2020-05-18 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='care_taker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cat',
            name='children',
            field=models.ManyToManyField(blank=True, null=True, related_name='cats_child', to='cats.Cat'),
        ),
        migrations.AddField(
            model_name='cat',
            name='dad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cats_dad', to='cats.Cat'),
        ),
        migrations.AddField(
            model_name='cat',
            name='diagnosis',
            field=models.ManyToManyField(related_name='cats', to='cats.Diagnosis'),
        ),
        migrations.AddField(
            model_name='cat',
            name='health_condition',
            field=models.ManyToManyField(related_name='cats', to='cats.HealthCondition'),
        ),
        migrations.AddField(
            model_name='cat',
            name='mom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cats_mom', to='cats.Cat'),
        ),
    ]
