# Generated by Django 2.2.5 on 2020-05-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_auto_20200520_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='age',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
