# Generated by Django 2.2.5 on 2020-05-20 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_cat_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='age',
        ),
    ]
