# Generated by Django 2.2.5 on 2020-05-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_remove_cat_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='age',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
