# Generated by Django 2.2.5 on 2020-05-20 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0005_cat_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='age',
            new_name='estimated_age',
        ),
    ]
