# Generated by Django 2.2.5 on 2020-05-24 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0006_auto_20200521_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Apperance',
            },
        ),
        migrations.AddField(
            model_name='cat',
            name='appearance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cats.Appearance'),
        ),
    ]
