# Generated by Django 2.2.5 on 2020-06-07 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0008_auto_20200524_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='care_taker',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='cats', to=settings.AUTH_USER_MODEL),
        ),
    ]
