# Generated by Django 2.2.5 on 2020-06-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0009_auto_20200607_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='care_category',
            field=models.CharField(choices=[('blue care', 'Blue Care'), ('green care', 'Green Care'), ('orange care', 'Orange Care'), ('pink care', 'Pink Care')], default='green care', max_length=10),
        ),
        migrations.AddField(
            model_name='cat',
            name='foster_needed',
            field=models.BooleanField(default=False),
        ),
    ]
