# Generated by Django 2.2.5 on 2020-07-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0010_auto_20200620_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='care_category',
            field=models.CharField(choices=[('blue care', 'Blue Care'), ('green care', 'Green Care'), ('orange care', 'Orange Care'), ('pink care', 'Pink Care')], default='green care', max_length=12),
        ),
    ]
